Update pg-deploy.yml

diff --git a/.github/workflows/pg-deploy.yml b/.github/workflows/pg-deploy.yml
--- a/.github/workflows/pg-deploy.yml
+++ b/.github/workflows/pg-deploy.yml
@@ -1,7 +1,7 @@
 name: Deployment Pg
 on: push
 permissions:
-   contents: write
+  contents: write
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -11,10 +11,11 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Installing NPM packages
-        run: npm ci
+        run: npm install
 
       - name: Building project
-        run: npm run build
+        run: |
+          npm run build || { echo "Build failed"; exit 1; }
 
       - name: Running tests
         run: npm run test
@@ -40,7 +41,7 @@ jobs:
           name: production-files
           path: ./build
 
-      - name: Deploying Pg
+      - name: Deploying to gh-pages
         uses: peaceiris/actions-gh-pages@v4
         with:
           github_token: ${{ secrets.GITHUB_TOKEN }}
